name: 🐛 内容纠错
description: 发现课程内容错误
title: "[纠错] "
labels: [bug, documentation]
assignees: []
body:
  - type: textarea
    id: error
    attributes:
      label: 错误描述
      placeholder: 错误在哪里？正确应该是什么？
    validations:
      required: true