name: 🚀 内容建议
description: 建议新增内容或改进
title: "[建议] "
labels: [enhancement]
assignees: []
body:
  - type: textarea
    id: suggestion
    attributes:
      label: 建议内容
      placeholder: 你的建议是？
    validations:
      required: true