name: ❓ 问题求助
description: 学习中遇到的问题
title: "[问题] "
labels: [question]
assignees: []
body:
  - type: textarea
    id: question
    attributes:
      label: 问题描述
      placeholder: 详细描述你的问题...
    validations:
      required: true